source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "redis", ">= 4.0.1"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem 'rspec-rails'
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :test do
  gem 'rails-controller-testing'
  gem 'factory_bot_rails'
  gem 'faker'
 end

group :development do
  gem 'annotate'
end

